// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ReadRootGetResponse, GetQuizQuizGetResponse, PutQuizEntryQuizEntryPostData, PutQuizEntryQuizEntryPostResponse, GetAdminQuizEntriesAdminQuizEntriesGetResponse, GetAdminQuizParticipantsAdminQuizParticipantsGetResponse, GetAdminQuizEntryAdminQuizEntryGetResponse } from './types.gen';

/**
 * Read Root
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const readRootGet = (): CancelablePromise<ReadRootGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/'
}); };

/**
 * Get Quiz
 * @returns Quiz Successful Response
 * @throws ApiError
 */
export const getQuizQuizGet = (): CancelablePromise<GetQuizQuizGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/quiz'
}); };

/**
 * Put Quiz Entry
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const putQuizEntryQuizEntryPost = (data: PutQuizEntryQuizEntryPostData): CancelablePromise<PutQuizEntryQuizEntryPostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/quiz-entry',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Get Admin Quiz Entries
 * @returns QuizEntry Successful Response
 * @throws ApiError
 */
export const getAdminQuizEntriesAdminQuizEntriesGet = (): CancelablePromise<GetAdminQuizEntriesAdminQuizEntriesGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/admin/quiz/entries'
}); };

/**
 * Get Admin Quiz Participants
 * @returns QuizParticipant Successful Response
 * @throws ApiError
 */
export const getAdminQuizParticipantsAdminQuizParticipantsGet = (): CancelablePromise<GetAdminQuizParticipantsAdminQuizParticipantsGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/admin/quiz/participants'
}); };

/**
 * Get Admin Quiz Entry
 * @returns QuizEntry Successful Response
 * @throws ApiError
 */
export const getAdminQuizEntryAdminQuizEntryGet = (): CancelablePromise<GetAdminQuizEntryAdminQuizEntryGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/admin/quiz/entry'
}); };